services:
  postgres:
    image: postgres:15
    container_name: pm_postgres
    environment:
      POSTGRES_USER: pmuser
      POSTGRES_PASSWORD: pmpassword
      POSTGRES_DB: pmdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safran-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: pm_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - safran-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: pm_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: pm_zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://pm_kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - safran-net

  # ==========================
  # Spring Boot App
  # ==========================
  safran-app:
    build: .
    container_name: safran-app
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: pm_postgres
      DB_PORT: 5432
      DB_USERNAME: pmuser
      DB_PASSWORD: pmpassword
      KAFKA_HOST: pm_kafka
      KAFKA_PORT: 9092
    ports:
      - "8080:8080"
    networks:
      - safran-net
    volumes:
      - maven_repo:/root/.m2

  prometheus:
    image: prom/prometheus
    container_name: pm_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - safran-net

  grafana:
    image: grafana/grafana
    container_name: pm_grafana
    ports:
      - "3000:3000"
    networks:
      - safran-net


volumes:
  postgres_data:
  maven_repo:

networks:
  safran-net:
    driver: bridge
